#!/usr/bin/env python
"""Alex Barcelo Dotfiles bootstrap

This Python script can be used to initiate a bootstrap of all the Dotfiles 
machinery.
"""

# We try to avoid python2/python3 conflicts
from __future__ import (unicode_literals,
                        print_function)
import os
import shutil
import subprocess
import sys


USERNAME = os.getenv("ABDF_USERNAME", "alexbarcelo")
REPO = os.getenv("ABDF_REPO",
                 "git@github.com:{}/dotfiles.git".format(USERNAME))

if __name__ == "__main__":
    print()
    print(" **************************************")
    print("   Welcome to Alex Barcelo's Dotfiles")
    print(" **************************************")
    print()

    exec_path = os.path.dirname(os.path.abspath(__file__))
    print("   > I am being executed from:", exec_path)
    target_path = os.path.expanduser("~/dotfiles")
    print("   > My target path is:", target_path)

    if exec_path == target_path:
        print("   * Seems that I am already in place. Are you sure you want to call to `bootstrap`?")
        exit(1)

    print("   * Starting bootstrap of Dotfiles")

    print("   * Proceeding to git-clone repository:", REPO)
    retcode = subprocess.call([
        'git', 'clone',
        '--quiet',
        '--depth', '2',
        '--recurse-submodules',
        REPO,
        target_path])
    if retcode != 0:
        print("   * Error while trying to execute git clone")
        exit(retcode)
    print("   * Clone finished, ready to use the Alex Barcelo Dotfile Python library")

    sys.path.append(target_path)
    import abdf
    import abdf.utils
    abdf.deploy()

    private_path = os.path.join(exec_path, "private")
    if os.path.exists(os.path.join(private_path, ".POPULATED")):
        print("   * I am being executed from a USB stick or a similar authoritative source")
        print("     so I will use its `private` folder as a valid source")
        print("   > That means, copying %s into %s" % (private_path, os.path.expanduser('~')))

        abdf.utils.copytree(private_path, os.path.expanduser('~'))
