#!/usr/bin/env python
"""Alex Barcelo Dotfiles bootstrap

This Python script can be used to initiate a bootstrap of all the Dotfiles 
machinery.
"""

# We try to avoid python2/python3 conflicts
from __future__ import (unicode_literals,
                        print_function)
import os
import subprocess

USERNAME = os.getenv("ABDF_USERNAME", "alexbarcelo")
REPO = os.getenv("ABDF_REPO",
                 "https://github.com/{}/dotfiles.git".format(USERNAME))

if __name__ == "__main__":
    print()
    print(" **************************************")
    print("   Welcome to Alex Barcelo's Dotfiles")
    print(" **************************************")
    print()

    exec_path = os.path.dirname(os.path.abspath(__file__))
    print("   > I am being executed from:", exec_path)
    target_path = os.path.join(os.getenv('HOME'), "dotfiles")
    print("   > My target path is:", target_path)

    if exec_path == target_path:
        print("   * Seems that I am already in place. Are you sure you want to call to `bootstrap`?")
        exit(1)

    print("   * Starting bootstrap of Dotfiles")

    print("   * Proceeding to git-clone repository:", REPO)
    subprocess.call(['git', 'clone', REPO, target_path])

    if os.path.exists(os.path.join(exec_path, "private", ".POPULATED")):
        print("   * I am being executed from a USB stick or a similar authoritative source")
        print("     so I will use its `private` folder as a valid source")

        # ToDo

